version: "3.8"
services:
  # Databases
  freshfood_catalog_db:
    container_name: freshfood_catalog_db
    image: postgres:15.3
    environment:
      POSTGRES_USER: freshfood
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: freshfood_catalog
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
  freshfood_marketplace_db:
    container_name: freshfood_marketplace_db
    image: postgres:15.3
    environment:
      POSTGRES_USER: freshfood
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: freshfood_marketplace
    ports:
      - "5432:5432"
  freshfood_order_db:
    container_name: freshfood_order_db
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: freshfood
      MONGO_INITDB_ROOT_PASSWORD: orders
      MONGO_INITDB_DATABASE: freshfood
    ports:
      - "27017:27017"
  # Metrics
  freshfood_jaeger:
    container_name: freshfood_jaeger
    image: jaegertracing/all-in-one:1.46
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  freshfood_prometheus:
    container_name: freshfood_prometheus
    image: freshfood-prometheus:v2.44.0
    network_mode: "host"
  freshfood_grafana:
    container_name: freshfood_grafana
    image: grafana/grafana:9.5.3
    network_mode: "host"
  # Queues
  freshfood_artemismq:
    container_name: freshfood_artemismq
    image: orangebees/apache-artemis:2.28.0
    network_mode: "host"
    # ports:
    #   - "61616:61616"
    #   - "8161:8161"
    #   - "14268:14268"
    environment:
      - ARTEMIS_USER=freshfood
      - ARTEMIS_PASSWORD=artemismq
  freshfood_keycloak:
      container_name: freshfood_keycloak
      image: mihaibob/keycloak:15.0.1
      ports:
        - "8180:8080"
        - "9990:9990"
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
volumes:
  pgdata:
    external: true